// <auto-generated />
namespace DreamAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EfCore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EfCore));
        
        string IMigrationMetadata.Id
        {
            get { return "202010301611189_Ef-Core"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
