// <auto-generated />
namespace DreamAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class notvirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notvirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "202010301429181_notvirtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
